.TH "" "" "" "" ""
.SH dot\-helper
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ dot\-helper
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ dot\-helper\ array\ VARNAME\ \-s\ SNAME\ [\-n\ NUM]\ [\ \-i\ IT\ ]\ [\ \-m\ MAX\ ]
\ \ \ \ dot\-helper\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ dot\-helper
\ \ \ \ \-s,\ \-\-structure\ SNAME\ \ \ name\ of\ the\ structure
\ \ \ \ \-n,\ \-\-number\ NUM\ \ \ \ \ \ \ \ number\ of\ the\ subgraph\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (default:\ \[aq]0\[aq])
\ \ \ \ \-i,\ \-\-iterator\ IT\ \ \ \ \ \ \ name\ of\ the\ iteratori\ to\ use\ \ \ \ \ \ \ \ \ (default:\ \[aq]i\[aq])
\ \ \ \ \-m,\ \-\-max\ MAX\ \ \ \ \ \ \ \ \ \ \ name\ of\ the\ upper\ bound\ of\ the\ array\ (default:\ \[aq]?\[aq])
Commands:
\ \ \ \ array\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ generates\ a\ dot\ representation\ of\ an\ array\ of\ structs

Arguments:
\ \ \ \ VARNAME\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ name\ of\ the\ variable\ array
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
generates array of structures boilerplate \-\- Jul 30th
15 (../../commit/4d3e312c11c6001c9981121b53892ff3a593ae74)
.SH Changes to the build process
.IP \[bu] 2
fix tabs \-\- Jul 30th
15 (../../commit/e5b2c2c8abd125b6798814db507bbf751a3a5757)
